/********************************************************************
* Dictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Dictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDictionary();
extern void G__cpp_setup_inheritanceDictionary();
extern void G__cpp_setup_typetableDictionary();
extern void G__cpp_setup_memvarDictionary();
extern void G__cpp_setup_globalDictionary();
extern void G__cpp_setup_memfuncDictionary();
extern void G__cpp_setup_funcDictionary();
extern void G__set_cpp_environmentDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TRexSettings.hh"
#include "include/Barrel.hh"
#include "include/Annular.hh"
#include "include/Germanium.hh"
#include "include/ParticleMC.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DictionaryLN_TClass;
extern G__linked_taginfo G__DictionaryLN_TBuffer;
extern G__linked_taginfo G__DictionaryLN_TMemberInspector;
extern G__linked_taginfo G__DictionaryLN_TObject;
extern G__linked_taginfo G__DictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__DictionaryLN_string;
extern G__linked_taginfo G__DictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictionaryLN_TRexSettings;
extern G__linked_taginfo G__DictionaryLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictionaryLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictionaryLN_Barrel;
extern G__linked_taginfo G__DictionaryLN_Annular;
extern G__linked_taginfo G__DictionaryLN_Crystal;
extern G__linked_taginfo G__DictionaryLN_Germanium;
extern G__linked_taginfo G__DictionaryLN_vectorlECrystalcOallocatorlECrystalgRsPgR;
extern G__linked_taginfo G__DictionaryLN_vectorlECrystalcOallocatorlECrystalgRsPgRcLcLiterator;
extern G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlECrystalcOallocatorlECrystalgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictionaryLN_ParticleMC;
extern G__linked_taginfo G__DictionaryLN_vectorlEBarrelcOallocatorlEBarrelgRsPgR;
extern G__linked_taginfo G__DictionaryLN_vectorlEBarrelcOallocatorlEBarrelgRsPgRcLcLiterator;
extern G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlEBarrelcOallocatorlEBarrelgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictionaryLN_vectorlEAnnularcOallocatorlEAnnulargRsPgR;
extern G__linked_taginfo G__DictionaryLN_vectorlEAnnularcOallocatorlEAnnulargRsPgRcLcLiterator;
extern G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlEAnnularcOallocatorlEAnnulargRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictionaryLN_vectorlEGermaniumcOallocatorlEGermaniumgRsPgR;
extern G__linked_taginfo G__DictionaryLN_vectorlEGermaniumcOallocatorlEGermaniumgRsPgRcLcLiterator;
extern G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlEGermaniumcOallocatorlEGermaniumgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictionaryLN_vectorlEParticleMCcOallocatorlEParticleMCgRsPgR;
extern G__linked_taginfo G__DictionaryLN_vectorlEParticleMCcOallocatorlEParticleMCgRsPgRcLcLiterator;
extern G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlEParticleMCcOallocatorlEParticleMCgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<Crystal,allocator<Crystal> > G__vectorlECrystalcOallocatorlECrystalgRsPgR;
typedef vector<Barrel,allocator<Barrel> > G__vectorlEBarrelcOallocatorlEBarrelgRsPgR;
typedef vector<Annular,allocator<Annular> > G__vectorlEAnnularcOallocatorlEAnnulargRsPgR;
typedef vector<Germanium,allocator<Germanium> > G__vectorlEGermaniumcOallocatorlEGermaniumgRsPgR;
typedef vector<ParticleMC,allocator<ParticleMC> > G__vectorlEParticleMCcOallocatorlEParticleMCgRsPgR;
